remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Automatic Engine
description: Tool to rename multiple files name with variety of conditions
show_downloads: true
